export const SIGNIN_REQ = "SIGNIN_REQ"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "SIGNIN_FAIL"

export const ACTIVATED_ACCOUNT_REQ = "ACTIVATED_ACCOUNT_REQ"
export const ACTIVATED_ACCOUNT_SUCCESS = "ACTIVATED_ACCOUNT_SUCCESS"
export const ACTIVATED_ACCOUNT_FAIL = "ACTIVATED_ACCOUNT_FAIL"

export const ACTIVATED_RESENDEMAIL_REQ = "ACTIVATED_RESENDEMAIL_REQ"
export const ACTIVATED_RESENDEMAIL_SUCCESS = "ACTIVATED_RESENDEMAIL_SUCCESS"
export const ACTIVATED_RESENDEMAIL_FAIL = "ACTIVATED_RESENDEMAIL_FAIL"

export const SIGNUP_REQ = "SIGNUP_REQ"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const SIGNUP_CHECKEMAIL_REQ = "SIGNUP_CHECKEMAIL_REQ"
export const SIGNUP_CHECKEMAIL_SUCCESS = "SIGNUP_CHECKEMAIL_SUCCESS"
export const SIGNUP_CHECKEMAIL_FAIL = "SIGNUP_CHECKEMAIL_FAIL"

export const IQUEUE_SENDEMAIL_REQ = "IQUEUE_SENDEMAIL_REQ"
export const IQUEUE_SENDEMAIL_SUCCESS = "IQUEUE_SENDEMAIL_SUCCESS"
export const IQUEUE_SENDEMAIL_FAIL = "IQUEUE_SENDEMAIL_FAIL"

export const MAP_USERSALON_REQ = "MAP_USERSALON_REQ"
export const MAP_USERSALON_SUCCESS = "MAP_USERSALON_SUCCESS"
export const MAP_USERSALON_FAIL = "MAP_USERSALON_FAIL"