export const ADMIN_MERGE_RET2_REQ = "ADMIN_MERGE_RET2_REQ"
export const ADMIN_MERGE_RET2_SUCCESS = "ADMIN_MERGE_RET2_SUCCESS"
export const ADMIN_MERGE_RET2_FAIL = "ADMIN_MERGE_RET2_FAIL"

export const GET_SALON_DETAILSBYID_REQ = "GET_SALON_DETAILSBYID_REQ"
export const GET_SALON_DETAILSBYID_SUCCESS = "GET_SALON_DETAILSBYID_SUCCESS"
export const GET_SALON_DETAILSBYID_FAIL = "GET_SALON_DETAILSBYID_FAIL"