export const PLACES_API_REQ = "PLACES_API_REQ"
export const PLACES_API_SUCCESS = "PLACES_API_SUCCESS"
export const PLACES_API_FAIL = "PLACES_API_FAIL"

export const RETRIEVE_SALONLIST_REQ = "RETRIEVE_SALONLIST_REQ"
export const RETRIEVE_SALONLIST_SUCCESS = "RETRIEVE_SALONLIST_SUCCESS"
export const RETRIEVE_SALONLIST_FAIL = "RETRIEVE_SALONLIST_FAIL"

export const IQB_SALONS_REQ = "IQB_SALONS_REQ"
export const IQB_SALONS_SUCCESS = "IQB_SALONS_SUCCESS"
export const IQB_SALONS_FAIL = "IQB_SALONS_FAIL"
