export const GET_CUSTOMER_DETAILS_REQ = "GET_CUSTOMER_DETAILS_REQ"
export const GET_CUSTOMER_DETAILS_SUCCESS = "GET_CUSTOMER_DETAILS_SUCCESS"
export const GET_CUSTOMER_DETAILS_FAIL = "GET_CUSTOMER_DETAILS_FAIL"

export const IQUEUE_UPDATE_CUSTOMER_DETAILS_REQ = "IQUEUE_UPDATE_CUSTOMER_DETAILS_REQ"
export const IQUEUE_UPDATE_CUSTOMER_DETAILS_SUCCESS = "IQUEUE_UPDATE_CUSTOMER_DETAILS_SUCCESS"
export const IQUEUE_UPDATE_CUSTOMER_DETAILS_FAIL = "IQUEUE_UPDATE_CUSTOMER_DETAILS_FAIL"

export const FORGOT_CHECK_EMAIL_REQ = "FORGOT_CHECK_EMAIL_REQ"
export const FORGOT_CHECK_EMAIL_SUCCESS = "FORGOT_CHECK_EMAIL_SUCCESS"
export const FORGOT_CHECK_EMAIL_FAIL = "FORGOT_CHECK_EMAIL_FAIL"

export const FORGOT_SEND_PASSWORD_REQ = "FORGOT_SEND_PASSWORD_REQ"
export const FORGOT_SEND_PASSWORD_SUCCESS = "FORGOT_SEND_PASSWORD_SUCCESS"
export const FORGOT_SEND_PASSWORD_FAIL = "FORGOT_SEND_PASSWORD_FAIL"