export const GET_CUSTOMER_DETAILS_REQ = "GET_CUSTOMER_DETAILS_REQ"
export const GET_CUSTOMER_DETAILS_SUCCESS = "GET_CUSTOMER_DETAILS_SUCCESS"
export const GET_CUSTOMER_DETAILS_FAIL = "GET_CUSTOMER_DETAILS_FAIL"