export const IQUEUE_CHECKLIST_REQ = "IQUEUE_CHECKLIST_REQ"
export const IQUEUE_CHECKLIST_SUCCESS = "IQUEUE_CHECKLIST_SUCCESS"
export const IQUEUE_CHECKLIST_FAIL = "IQUEUE_CHECKLIST_FAIL"

export const IQUEUE_BARBER_SELECT_REQ = "IQUEUE_BARBER_SELECT_REQ"
export const IQUEUE_BARBER_SELECT_SUCCESS = "IQUEUE_BARBER_SELECT_SUCCESS"
export const IQUEUE_BARBER_SELECT_FAIL = "IQUEUE_BARBER_SELECT_FAIL"

export const GETSERVICES_BY_BARBERID_SALONID_REQ =  "GETSERVICES_BY_BARBERID_SALONID_REQ"
export const GETSERVICES_BY_BARBERID_SALONID_SUCCESS = "GETSERVICES_BY_BARBERID_SALONID_SUCCESS"
export const GETSERVICES_BY_BARBERID_SALONID_FAIL = "GETSERVICES_BY_BARBERID_SALONID_FAIL"

export const IQUEUE_JOINED_SELECT_REQ = "IQUEUE_JOINED_SELECT_REQ"
export const IQUEUE_JOINED_SELECT_SUCCESS = "IQUEUE_JOINED_SELECT_SUCCESS"
export const IQUEUE_JOINED_SELECT_FAIL = "IQUEUE_JOINED_SELECT_FAIL"

export const IQUEUE_CHECK_POSITON_REQ = "IQUEUE_CHECK_POSITON_REQ"
export const IQUEUE_CHECK_POSITON_SUCCESS = "IQUEUE_CHECK_POSITON_SUCCESS"
export const IQUEUE_CHECK_POSITON_FAIL = "IQUEUE_CHECK_POSITON_FAIL"

export const IQUEUE_INSERTJOINQ_REQ = "IQUEUE_INSERTJOINQ_REQ"
export const IQUEUE_INSERTJOINQ_SUCCESS = "IQUEUE_INSERTJOINQ_SUCCESS"
export const IQUEUE_INSERTJOINQ_FAIL = "IQUEUE_INSERTJOINQ_FAIL"