export const GET_BARBER_BY_SALONID_REQ = "GET_BARBER_BY_SALONID_REQ"
export const GET_BARBER_BY_SALONID_SUCCESS = "GET_BARBER_BY_SALONID_SUCCESS"
export const GET_BARBER_BY_SALONID_FAIL = "GET_BARBER_BY_SALONID_FAIL"

export const GET_SERVICES_BY_BARBERID_SALONID_REQ = "GET_SERVICES_BY_BARBERID_SALONID_REQ"
export const GET_SERVICES_BY_BARBERID_SALONID_SUCCESS = "GET_SERVICES_BY_BARBERID_SALONID_SUCCESS"
export const GET_SERVICES_BY_BARBERID_SALONID_FAIL = "GET_SERVICES_BY_BARBERID_SALONID_FAIL"

export const GET_SALON_IMAGE_LIST_REQ = "GET_SALON_IMAGE_LIST_REQ"
export const GET_SALON_IMAGE_LIST_SUCCESS = "GET_SALON_IMAGE_LIST_SUCCESS"
export const GET_SALON_IMAGE_LIST_FAIL = "GET_SALON_IMAGE_LIST_FAIL"

export const IQBUSER_RATE_REQ = "IQBUSER_RATE_REQ"
export const IQBUSER_RATE_SUCCESS = "IQBUSER_RATE_SUCCESS"
export const IQBUSER_RATE_FAIL = "IQBUSER_RATE_FAIL"